In [23]:
data_file='/content/drive/MyDrive/Colab Notebooks/Data Sets/makeSenseOfCensus.csv'

In [58]:
import numpy as np

data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
print("\n Data: \n\n", data)

print("\n Type of Data: \n\n",type(data))

#Solution of Step 2 (Adding new record)
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
#Adding new_record to the previous record
#print (np.concatenate((data,new_record)))
new_data=np.append(data, new_record, axis=0)



 Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

 Type of Data: 

 <class 'numpy.ndarray'>


In [61]:
#Solution of Step 3 (Finding minimum, maximum, mean, and standard deviation of age)
#finding the maximum age
data_age= new_data[:, 0]
max_age = np.max(data_age)
print("Maximum Age = ", max_age)

#Finding minimum age
min_age = np.min(data_age)
print("Minimum Age = ", min_age)

#Finding the mean of the age
mean_age=np.mean(data_age)
print("Mean age of the Employees is = ",round(mean_age, 2))

#Finding Standard deviation of age
age_std = np.std(data_age)
print("Standard Deviation of the age = ",round(age_std,2))

Maximum Age =  90.0
Minimum Age =  17.0
Mean age of the Employees is =  38.06
Standard Deviation of the age =  13.34


In [62]:
#Solution of Step 4 (Country's race distribution)
data_race=new_data[:, 2]
print(data_race)
race_0 = data_race[data_race==0]
print(race_0)
print("There are ", len(race_0), "persons with race 0 i.e. Amer-Indian-Eskimo")
race_1 = data_race[data_race==1]
print(race_1)
print("There are ", len(race_1), "persons with race 1 i.e. Asian-Pac-Islander")
race_2 = data_race[data_race==2]
print(race_2)
print("There are ", len(race_2), "persons with race 2 i.e. Black")
race_3 = data_race[data_race==3]
print(race_3)
print("There are ", len(race_3), "persons with race 3 i.e. other")
race_4 = data_race[data_race==4]
print(race_4)
print("There are ", len(race_4), "persons with race 4 i.e. White")

[4. 4. 4. ... 4. 4. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
There are  10 persons with race 0 i.e. Amer-Indian-Eskimo
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
There are  27 persons with race 1 i.e. Asian-Pac-Islander
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
There are  110 persons with race 2 i.e. Black
[3. 3. 3. 3. 3. 3.]
There are  6 persons with race 3 i.e. other
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4.

In [25]:
len_0 = len(race_0)
print(len_0)
len_1 = len(race_1)
print(len_1)
len_2 = len(race_2)
print(len_2)
len_3 = len(race_3)
print(len_3)
len_4 = len(race_4)
print(len_4)

10
27
110
6
848


In [26]:
min_citizen = min(len_0,len_1,len_2,len_3,len_4)
if min_citizen == len_0 :
  print('Race_0 has the minimum citizen of',len_0)
elif min_citizen == len_1 :
  print('Race_1 has the minimum citizen of',len_1)
elif min_citizen == len_2 :
  print('Race_2 has the minimum citizen of',len_2)
elif min_citizen == len_3 :
  print('Race_3 has the minimum citizen of',len_3)
else:
  print('Race_4 has the minimum citizen of',len_4)

Race_3 has the min_citizen of 6


In [27]:
min_citizen = min(len_0,len_1,len_2,len_3,len_4)
if min_citizen == len_0 :
  minority_race = 0
  print('Minority_race',minority_race)
elif min_citizen == len_1 :
  minority_race = 1
  print('Minority_race',minority_race)
elif min_citizen == len_2 :
  minority_race = 2
  print('Minority_race',minority_race)
elif min_citizen == len_3 :
  minority_race = 3
  print('Minority_race',minority_race)
else :
  minority_race = 4
  print('Minority_race',minority_race)

Minority_race 3


In [28]:
print(minority_race)

3


In [32]:
#Solution 5 (Finding the subset array senior_citizens)
senior_citizens = data[data[:, 0]>60]
print(senior_citizens)

[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

In [35]:
senior_citizens[:,0]

array([79., 67., 76., 61., 70., 64., 71., 68., 66., 64., 90., 66., 75.,
       65., 64., 61., 65., 77., 62., 76., 63., 66., 67., 65., 62., 63.,
       80., 67., 63., 72., 62., 74., 67., 72., 69., 65., 65., 71., 70.,
       66., 65., 61., 61., 68., 64., 64., 62., 73., 72., 63., 62., 61.,
       71., 63., 63., 67., 81., 64., 67., 78., 63.])

In [67]:
#Solution 5 (Finding sum of working hours of senior citizens)
working_hours_sum = sum(senior_citizens[:,6])
print("The sum of working hours of senior citizens are = ",working_hours_sum, "hours")

The sum of working hours of senior citizens are =  1917.0 hours


In [37]:
senior_citizens[:, 6]

array([20.,  2., 40., 40., 40., 40.,  2., 20., 20., 40., 40., 50., 20.,
       40., 40., 40., 16., 40., 24., 10., 45., 55.,  8., 40., 40., 40.,
       24., 24., 35., 20., 40.,  9., 48., 40., 40., 30., 24., 15., 15.,
        4., 59., 50., 40., 20., 40., 45., 40., 40., 24.,  6., 48., 40.,
       40., 15., 55., 40., 30.,  5., 40., 40., 20.])

In [57]:
#Solution 5 (Finding the lenght of senior ciztizens)
senior_citizens_len=len(senior_citizens)
print("There are ", senior_citizens_len, "senior citizens")


There are  61 senior citizens


In [44]:
#Solution 5 (Average workign hours of senior citizens)
avg_working_hours = working_hours_sum/senior_citizens_len
print("The average working hour of senior citizens are: ", (round(avg_working_hours,2)))

The average working hour of senior citizens are:  31.43


In [45]:
#Solution 5 (Finding the work voilation of govenerment policy)
if avg_working_hours>25:
  print("Goverment Policy has been voileted")
else:
  print("Government plicy is followed")

Goverment Policy has been voileted


In [50]:
#Solution of 6 (Creating two subset array: high and low)
high = data[data[:,1]>10]
print(high)
print('*'*50)
low = data[data[:, 1]<=10]
print(low)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
**************************************************
[[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [35.  9.  4. ...  0. 45.  0.]
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]]


In [64]:
from numpy.ma.extras import average
avg_pay_high = average(high[:,7])
print("Average Pay of higher educated peoples = ", round(avg_pay_high,2))

avg_pay_low = average(low[:,7])
print("Average Pay of lower educated peoples = ", round(avg_pay_low,2))

Average Pay of higher educated peoples =  0.43
Average Pay of lower educated peoples =  0.14
